### ISSUE TITLE
Batterieobjekte werden nicht erstellt

### ISSUE THREAD

**Issue by vito6666** [KornSW/ioBroker.fusionsolar#10]
Moin Moin,
ich habe ein Problem mit der Huawei API gen2. Es werden die Objekte für den Wechselrichter und das Smartmeter erstellt, allerdings kein Ordner für die Batterie. Ich habe bereits beim Installateur nachgefragt, ob er mir den  API Zugriff auf alle Objekte inkl. Batterie gegeben hat -> angeblich ja. Kann ich das irgendwie prüfen? Ein entsprechendes Logfile habe ich angehängt, die Skip- Optionen in der Instanz habe ich zum Testen deaktiviert:
[log.log](https://github.com/KornSW/ioBroker.fusionsolar/files/11300769/log.log)

Schönen Gruß
Vito

**Comment by stolly82** [comment]
Hey @vito6666 ,

kannst du mal die v.1.2.4 testen?!? 

iobroker url https://github.com/KornSW/ioBroker.fusionsolar/tarball/v.1.2.4 --host IoBroker --debug

Ich hatte da bei der Anlage der Objekte einiges geändert, da ich den Fehler auch einmal hatte. 

Vielleicht läuft es damit. 

Liebe Grüsse

Jan

**Comment by vito6666** [comment]
Moin Jan,

sehr gut, vielen Dank! Mit der 1.2.4 werden die Objekte für den Akku und sogar jeden Optimierer und den Dongle erstellt.
Ist es normal, dass nur einer der zwei Akkus vom Laderegler angezeigt wird? Verbaut sind 2 x 5kWh, es gibt aber nur ein Objektordner mit "maxChargePower" = 5000 und "devName" = Battery-1.

Schönen Gruß
Vito

**Comment by stolly82** [comment]
@vito6666 
Du meinst aber, du hast einen LUNA2000 mit 2x 5kW also 10kW Gesamtleistung, oder? 

Denn die können ja nur 5kWh Laden und Entladen. 

Oder hast du zwei einzelne 5kW Batterien?

**Comment by vito6666** [comment]
@stolly82 
Genau, ich habe einen Akkuregler an dem zwei 5 kWh Stunden Akkupacks hängen. Ich bin allerdings grade selbst durcheinandergekommen und habe die Ladeleistung von 5kW mit der Kapazität von 5kWh der einzelnen Akkupacks verwechselt. Letztendlich ist für meine Skripte aber eh nur der Gesamtladezustand relevant. Vielen Dank an @stolly82 und  @KornSW.
