### ISSUE TITLE
Device "Meter" fehlen die Daten zur 2. und 3. Phase

### ISSUE THREAD

**Issue by jkbiz** [KornSW/ioBroker.fusionsolar#15]
Hallo zusammen,

vielen Dank für die Ausarbeitung des Adapters - ich weiß die viele Arbeit sehr zu schätzen und möchte zur Entwicklung beitragen.
Ich versuche den SmartMeter genauer zu erfassen und dabei ist mir aufgefallen, dass hier die Phase 2 und Phase 3 fehlen. Siehe Screenshots
Darstellung im ioBroker
![image](https://github.com/KornSW/ioBroker.fusionsolar/assets/82655374/9b933aa7-98c6-4bc6-8c3b-35f4893494fb)

Darstellung im Monitoring FusionSolar
![image](https://github.com/KornSW/ioBroker.fusionsolar/assets/82655374/01d5cff9-8c44-42a8-b6a9-4f95f1fef1d5)

**Comment by stolly82** [comment]
Hey, kommt der denn aus den DEBUG Daten im Adapter raus?

**Comment by jkbiz** [comment]
Ich habe den Adapter auf debug gestellt und neugestartet



{"data":[{"devId":1000000036710112,"dataItemMap":{"meter_status":1,"active_cap":32.34,"meter_i":-0.57,"power_factor":-0.067,"c_i":0.31,"meter_u":240.3,"b_i":0.51,"reverse_reactive_valley":null,"positive_reactive_peak":null,"reverse_reactive_peak":null,"positive_active_peak":null,"reverse_active_peak":null,"reactive_power":122,"c_u":240.5,"total_apparent_power":null,"bc_u":416.2,"b_u":240.3,"reverse_active_cap":1.02,"positive_reactive_top":null,"reverse_reactive_power":null,"active_power_b":36,"active_power_a":-81,"positive_active_top":null,"reverse_reactive_cap":null,"positive_active_power":null,"positive_active_valley":null,"run_state":1,"reverse_reactive_top":null,"reverse_active_top":null,"reverse_active_power":null,"reactive_power_a":null,"forward_reactive_cap":null,"reactive_power_b":null,"reverse_active_valley":null,"reactive_power_c":null,"active_power":-13,"ab_u":416.2,"ca_u":416.2,"positive_reactive_power":null,"active_power_c":31,"grid_frequency":49.97,"positive_reactive_valley":null},"sn":"null"}],"failCode":0,"message":null,"params":{"currentTime":1688327842152,"devIds":"1000000036710112","devTypeId":47},"success":true}
--
 

<br class="Apple-interchange-newline">

**Comment by vr6syncro** [comment]
`

{
    "data": [
        {
            "devId": 1000000033942393,
            "dataItemMap": {
                "meter_status": 1.0,
                "active_cap": 0.0,
                "meter_i": -2.63,
                "power_factor": -0.657,
                "c_i": -0.76,
                "meter_u": 227.8,
                "b_i": -1.06,
                "reverse_reactive_valley": null,
                "positive_reactive_peak": null,
                "reverse_reactive_peak": null,
                "reverse_active_peak": null,
                "positive_active_peak": null,
                "reactive_power": 490.0,
                "c_u": 229.5,
                "total_apparent_power": null,
                "bc_u": 398.1,
                "b_u": 230.3,
                "reverse_active_cap": 1055.18,
                "reverse_reactive_power": null,
                "positive_reactive_top": null,
                "active_power_b": -84.0,
                "active_power_a": -452.0,
                "positive_active_top": null,
                "reverse_reactive_cap": null,
                "positive_active_power": null,
                "positive_active_valley": null,
                "run_state": 1,
                "reverse_reactive_top": null,
                "reverse_active_power": null,
                "reverse_active_top": null,
                "reactive_power_a": null,
                "forward_reactive_cap": null,
                "reactive_power_b": null,
                "reactive_power_c": null,
                "reverse_active_valley": null,
                "active_power": -674.0,
                "ab_u": 396.7,
                "ca_u": 396.1,
                "positive_reactive_power": null,
                "active_power_c": -138.0,
                "grid_frequency": 50.02,
                "positive_reactive_valley": null
            },
            "sn": "null"
        }
    ],

`

das gibt die api aus, aber er legt im code nicht alles an und müsste ergänzt werden
