### ISSUE TITLE
API returned failCode #407 (access frequency is too high) - giving up now :-(

### ISSUE THREAD

**Issue by dieterlind** [KornSW/ioBroker.fusionsolar#2]
Hello!

After successful login I receive the following error message: API returned failCode #407 (access frequency is too high) - giving up now :-(

![image](https://user-images.githubusercontent.com/93987222/206896019-7355461f-1a07-4a1f-8256-5dc4832bb749.png)

Any ideas what might be the issue?

Thanks!

**Comment by KornSW** [comment]
Hello, as I mentioned in the readme, there are many quota limitations from Huawei.
I was forced to implement automatic retry logic in case the entire server fails to respond. This usually happens when too many concurrent API clients are accessing the server. Without this feature it would be impossible to work with the API anyway. unfortunately, this feature also leads us to a second problem (your current problem): if you do too many reps, our personal quota counter will increase and we will be blocked for a short time.

for your troubleshooting you should:
      1. Disable your adapter for 1 hour and see if the problem comes back
      2. Increase your log level to get the silly log output
      3. Increase the reload interval to 5 minutes
      (for me it currently works fine with 180 seconds, but it depends a bit on the number of devices in your plant)
      
and maybe you can post some info:
      1. Your currently configured reload interval
      2. What hardware do you have?
      3. the log output at silly level
    
Thanks!

**Comment by KornSW** [comment]
any outcome?

**Comment by stonytec** [comment]
i have the same issue

`
fusionsolar.0 | 2023-01-18 09:13:29.951 | error | StationList was not loaded properly
fusionsolar.0 | 2023-01-18 09:13:26.950 | error | API returned failCode #407 (access frequency is too high) - giving up now :-(
fusionsolar.0 | 2023-01-18 09:13:26.949 | debug | {"data":"ACCESS_FREQUENCY_IS_TOO_HIGH","failCode":407,"params":null,"success":false}
fusionsolar.0 | 2023-01-18 09:13:26.949 | debug | loading StationList
fusionsolar.0 | 2023-01-18 09:13:23.821 | debug | initially loading StationList from the API...
fusionsolar.0 | 2023-01-18 09:13:23.818 | info | FusionSolar Api Login successful
fusionsolar.0 | 2023-01-18 09:13:23.817 | debug | got token: x-[XXXXX]
fusionsolar.0 | 2023-01-18 09:13:23.223 | debug | Schedule restart: * * * * *
fusionsolar.0 | 2023-01-18 09:13:23.198 | info | starting. Version 1.0.0 (non-npm: KornSW/ioBroker.fusionsolar#5316673cf49c8cccefdf4481cfcbdec66e8cb1f4) in /opt/iobroker/node_modules/iobroker.fusionsolar, node: v16.19.0, js-controller: 4.0.24

`

**Comment by KornSW** [comment]
Please read my previous answer - **it's from the API side:   "_access frequency is too high_"**
If you do some experiments, including many restarts of your adapter, you just have to wait some time before proceeding. If the problem persists, you can try fine-tuning your reload interval.
And even if everything is fine, it can happen (flaky) with the first query  after adapter has been restarted!

**Comment by stonytec** [comment]
I have already tried that before posting my error log
- intervall is set to 900sec
- I even created a new user with all respective rights and had the adapter shut down for over a week

if there are any ideas i am glad to test them and give feedback :-)

**Comment by KornSW** [comment]
hmm... may be too many devices to loop over?
ive just one inverter, one smart-meter, one bat-pack with 2 cells - do you have more?

**Comment by stonytec** [comment]
there is just one inverter, no smartmeter, no batt-pack...

**Comment by KornSW** [comment]
As you can see - there are 3sec's between login and loading the station list...
ive currently no idea why the API replies in that way, but ill make the per-api-call wait time also be present in the config, so that you can increase it also - (will take a few days).
Unfortunately, this requires some research and experiments....

**Comment by stonytec** [comment]
don't worry too much! next week i will do some testing and also a complete removal and install the adapter again with all clean setup. then i will start testing from scratch

**Comment by stonytec** [comment]
- adapter and all objects removed
- new northbound user created
- new adapter install with standard settings (180sec update intervall)

 - [x] works so far

i have no clue what caused this issue

**Comment by KornSW** [comment]
ok, thanks for the reply!
nevertheless ive created a new version for you which allows the modification of the wait-time between calls (pre-resease here: https://kornsw.de/downloads/iobroker.fusionsolar-1.0.1.tgz)

**Comment by verdure-beute** [comment]
Hi. first of all, thank you for the great work on that adapter.

I have the same problems as mentioned above. 

My setup:

- 1 inverter 
- 1 battery
- 1 dongle
- 1 meter
- 27 optimizer

request interval in the adapter settings is set to 600sec. But still I get the "API returned failCode #407 (access frequency is too high) - giving up now :-(" message/log every 10 min.

Any recommendations?
