### ISSUE TITLE
Adapter Install is different now?

### ISSUE THREAD

**Issue by dbeckers99** [KornSW/ioBroker.fusionsolar#3]
Ich habe versucht, den Adapter nach der Anleitung im ioBroker zu installieren. 

Leider finde ich bei der Auswahl in GitHub kein "undefined [KornSW]"

**Comment by KornSW** [comment]
Ich kanns aktuell sehen - natürlich ist da trotzdem was faul...
Über die dritte Tab kann man den Adapter auch von einer beliebigen URL installieren:

bitte mal mit dieser URL testen:
http://www.kornsw.de/downloads/iobroker.fusionsolar-1.0.0.tgz

**Comment by dbeckers99** [comment]
Das hat funktioniert, vielen Dank!
Jetzt muss ich nur noch meinen WR bei Fusionsolar einrichten....

**Comment by dbeckers99** [comment]
Ich hab's hinbekommen. Einen API-User kann man im Fusionsolar-Portal unter System/Unternehmensleitung/Northbound-Schnittstelle selber anlegen.

Genialer Adapter, vielen Dank dafür! Endlich bekomme ich Livedaten auch von meiner Enpal-Mietanlage in den ioBroker!

**Comment by KornSW** [comment]
Danke für Lob und Info (das scheint neu zu sein mit dem API-User via Portal -> da muss ich mal die Doku anpassen)

**Comment by KornSW** [comment]
PS: wenn der Adapter gefällt, dann freue ich mich über einen stern bei GitHub ;-)
