### ISSUE TITLE
PowerSensor Daten

### ISSUE THREAD

**Issue by dbeckers99** [KornSW/ioBroker.fusionsolar#4]
Die API bietet ja auch die Möglichkeit, Daten vom Power-Sensor (devicetyp 47) abzufragen. 

In den ioBroker Objekten von meinem WR sind diese Daten allerdings nicht zu finden, d.h. sie wurden nicht abgefragt/angelegt. 

In Fusionsolar sehe ich aber unter Inverter-1 sowohl Battery-1 als auch Meter-1. Ein Power-Sensor ist also installiert und auch erkannt/bekannt.

Was kann ich tun? Objektbaum komplett löschen unter ioBroker und nochmal anlegen lassen?

EDIT: Adpater explizit stop und dann wieder start hat das Problem gelöst. Ein einfacher Restart-Button-Klick nicht.

**Comment by KornSW** [comment]
Aktuell implementirt ist Inverter, Dongle, Battery und Meter, d.h. es sollte geladen werden. Objektbaum löschen ist nicht nötig. Die Komplett-Abfrage der devices findet jedes mal beim Hochfahren des Adapters statt. Die meisten solcher probleme kommen leider durch das nicht gerade stabile Antwortverhalten der server
